INSERT INTO portafoliodb.OrderStatus VALUES (DEFAULT, 'Abierta', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.OrderStatus VALUES (DEFAULT, 'Pago Solicitado', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.OrderStatus VALUES (DEFAULT, 'Cerrada', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
