INSERT INTO portafoliodb.UserRoles VALUES (DEFAULT, 'Cliente', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.UserRoles VALUES (DEFAULT, 'Administrador', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.UserRoles VALUES (DEFAULT, 'Bodega', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.UserRoles VALUES (DEFAULT, 'Finanzas', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.UserRoles VALUES (DEFAULT, 'Cocina', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.UserRoles VALUES (DEFAULT, 'Mesero', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());