INSERT INTO portafoliodb.MenuCategories VALUES (DEFAULT, 'Plato de Fondo', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.MenuCategories VALUES (DEFAULT, 'Acompañamiento', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.MenuCategories VALUES (DEFAULT, 'Ensalada', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.MenuCategories VALUES (DEFAULT, 'Postre', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO portafoliodb.MenuCategories VALUES (DEFAULT, 'Bebestible', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());