//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoresSigloXXI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MantenedoresSigloXXI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MantenedoresSigloXXI.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string ButtonAccept {
            get {
                return ResourceManager.GetString("ButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        public static string ButtonApprove {
            get {
                return ResourceManager.GetString("ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string ButtonReject {
            get {
                return ResourceManager.GetString("ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir un producto.
        /// </summary>
        public static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado una nueva mesa.
        /// </summary>
        public static string CTableCreated {
            get {
                return ResourceManager.GetString("CTableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha borrado la mesa exitosamente.
        /// </summary>
        public static string CTableDeleted {
            get {
                return ResourceManager.GetString("CTableDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CTablesFilterById {
            get {
                return ResourceManager.GetString("CTablesFilterById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha actualizado la mesa!.
        /// </summary>
        public static string CTableUpdated {
            get {
                return ResourceManager.GetString("CTableUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente eliminado con éxito.
        /// </summary>
        public static string CustomerDeleted {
            get {
                return ResourceManager.GetString("CustomerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo.
        /// </summary>
        public static string CustomerField {
            get {
                return ResourceManager.GetString("CustomerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string CustomerFieldEmail {
            get {
                return ResourceManager.GetString("CustomerFieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CustomerFieldId {
            get {
                return ResourceManager.GetString("CustomerFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string CustomerFieldLastName {
            get {
                return ResourceManager.GetString("CustomerFieldLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CustomerFieldName {
            get {
                return ResourceManager.GetString("CustomerFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string CustomerFieldPassword {
            get {
                return ResourceManager.GetString("CustomerFieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        public static string CustomerFieldUsername {
            get {
                return ResourceManager.GetString("CustomerFieldUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuario.
        /// </summary>
        public static string CustomerFieldUsertype {
            get {
                return ResourceManager.GetString("CustomerFieldUsertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CustomersFilterByName {
            get {
                return ResourceManager.GetString("CustomersFilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string CustomersFilterByUsername {
            get {
                return ResourceManager.GetString("CustomersFilterByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLIENTES.
        /// </summary>
        public static string CustomersPageTitle {
            get {
                return ResourceManager.GetString("CustomersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos actualizados con éxito.
        /// </summary>
        public static string CustomerUpdated {
            get {
                return ResourceManager.GetString("CustomerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificando mesa.
        /// </summary>
        public static string EditCTable {
            get {
                return ResourceManager.GetString("EditCTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Cliente.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar información de Insumo.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido un error con la conexión.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar:.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEN {
            get {
                return ResourceManager.GetString("LanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string LanguageES {
            get {
                return ResourceManager.GetString("LanguageES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar mesa.
        /// </summary>
        public static string NewCTable {
            get {
                return ResourceManager.GetString("NewCTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cliente.
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir un producto.
        /// </summary>
        public static string NewProduct {
            get {
                return ResourceManager.GetString("NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ha orden ha sido aprobada correctamente.
        /// </summary>
        public static string OrderApproved {
            get {
                return ResourceManager.GetString("OrderApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ha orden ha sido rechazada correctamente.
        /// </summary>
        public static string OrderRejected {
            get {
                return ResourceManager.GetString("OrderRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenes de reposición.
        /// </summary>
        public static string OrdersPageTitle {
            get {
                return ResourceManager.GetString("OrdersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string OtrosPageTitle {
            get {
                return ResourceManager.GetString("OtrosPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumo agregado con éxito!.
        /// </summary>
        public static string ProductCreated {
            get {
                return ResourceManager.GetString("ProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir un producto.
        /// </summary>
        public static string ProductCreatePage {
            get {
                return ResourceManager.GetString("ProductCreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumo Eliminado.
        /// </summary>
        public static string ProductDeleted {
            get {
                return ResourceManager.GetString("ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha creación.
        /// </summary>
        public static string ProductFieldCreado {
            get {
                return ResourceManager.GetString("ProductFieldCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ProductFieldId {
            get {
                return ResourceManager.GetString("ProductFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ProductFieldName {
            get {
                return ResourceManager.GetString("ProductFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string ProductFieldQuantity {
            get {
                return ResourceManager.GetString("ProductFieldQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha modificación.
        /// </summary>
        public static string ProductFieldUpdated {
            get {
                return ResourceManager.GetString("ProductFieldUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ProductFilterById {
            get {
                return ResourceManager.GetString("ProductFilterById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ProductFilterByName {
            get {
                return ResourceManager.GetString("ProductFilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumos.
        /// </summary>
        public static string ProductsPageTitle {
            get {
                return ResourceManager.GetString("ProductsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos actualizados con éxito.
        /// </summary>
        public static string ProductUpdated {
            get {
                return ResourceManager.GetString("ProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Idioma.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenedores para el Sistema del Restaurante Siglo XXI.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de esta aplicación.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar un tema.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalización.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidad.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscuro.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string ShellCustomersPage {
            get {
                return ResourceManager.GetString("ShellCustomersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otros.
        /// </summary>
        public static string ShellOtrosPage {
            get {
                return ResourceManager.GetString("ShellOtrosPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ShellProductsPage {
            get {
                return ResourceManager.GetString("ShellProductsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesas.
        /// </summary>
        public static string ShellTablesPage {
            get {
                return ResourceManager.GetString("ShellTablesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asientos.
        /// </summary>
        public static string TableFieldCapacity {
            get {
                return ResourceManager.GetString("TableFieldCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Cliente.
        /// </summary>
        public static string TableFieldCustomerId {
            get {
                return ResourceManager.GetString("TableFieldCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Mesa.
        /// </summary>
        public static string TableFieldId {
            get {
                return ResourceManager.GetString("TableFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Mesero.
        /// </summary>
        public static string TableFieldWaiterId {
            get {
                return ResourceManager.GetString("TableFieldWaiterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesas.
        /// </summary>
        public static string TablesPageTitle {
            get {
                return ResourceManager.GetString("TablesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cliente.
        /// </summary>
        public static string UpdateCustomerPageTitle {
            get {
                return ResourceManager.GetString("UpdateCustomerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión 0.11.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea aprobar la orden?.
        /// </summary>
        public static string WarningMsgBoxApprove {
            get {
                return ResourceManager.GetString("WarningMsgBoxApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un cliente.
        /// </summary>
        public static string WarningMsgBoxChooseOneCustomer {
            get {
                return ResourceManager.GetString("WarningMsgBoxChooseOneCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un insumo.
        /// </summary>
        public static string WarningMsgBoxChooseOneProduct {
            get {
                return ResourceManager.GetString("WarningMsgBoxChooseOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una mesa.
        /// </summary>
        public static string WarningMsgBoxChooseOneTable {
            get {
                return ResourceManager.GetString("WarningMsgBoxChooseOneTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea borrar la mesa?.
        /// </summary>
        public static string WarningMsgBoxDeleteCTable {
            get {
                return ResourceManager.GetString("WarningMsgBoxDeleteCTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea borrar al cliente?.
        /// </summary>
        public static string WarningMsgBoxDeleteCustomer {
            get {
                return ResourceManager.GetString("WarningMsgBoxDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que desea rechazar la orden?.
        /// </summary>
        public static string WarningMsgBoxDeleteOrder {
            get {
                return ResourceManager.GetString("WarningMsgBoxDeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea borrar el insumo?.
        /// </summary>
        public static string WarningMsgBoxDeleteProduct {
            get {
                return ResourceManager.GetString("WarningMsgBoxDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se aplicarán los cambios.
        /// </summary>
        public static string WarningMsgBoxEdit {
            get {
                return ResourceManager.GetString("WarningMsgBoxEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo ingresado no es válido.
        /// </summary>
        public static string WarningMsgBoxInvalidEmail {
            get {
                return ResourceManager.GetString("WarningMsgBoxInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido no es válido.
        /// </summary>
        public static string WarningMsgBoxInvalidLastName {
            get {
                return ResourceManager.GetString("WarningMsgBoxInvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no es válido.
        /// </summary>
        public static string WarningMsgBoxInvalidName {
            get {
                return ResourceManager.GetString("WarningMsgBoxInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad no es valida. Debe ser un número menor a 99.999.
        /// </summary>
        public static string WarningMsgBoxInvalidQuantity {
            get {
                return ResourceManager.GetString("WarningMsgBoxInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia!.
        /// </summary>
        public static string WarningMsgBoxTitle {
            get {
                return ResourceManager.GetString("WarningMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido al software de mantenedores del restaurant &quot;Siglo XXI&quot;!.
        /// </summary>
        public static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
    }
}
